[package]
name = "integration_tests"
version = "0.0.0"
authors = ["Exonum Team <exonum@bitfury.com>"]
publish = false

build = "build.rs"

[dependencies]
exonum = "0.10.0"
exonum-derive = "0.10.0"
hex = "=0.3.2"
failure = "0.1.3"
protobuf = "2.2.0"
rand = "=0.6.1"
rand_xorshift = "=0.1.0"
rocket = "=0.4.0"
rocket_codegen = "=0.4.0"
serde = "1.0"
serde_derive = "1.0"
uuid = "=0.7.1"

[dependencies.rocket_contrib]
version = "=0.4.0"
default-features = false
features = ["json"]

[build-dependencies]
exonum-build = "0.10.0"